src/main/java/it/unitn/web/centodiciotto/beans/CustomDTFormatterBean.java
package it.unitn.web.centodiciotto.beans;

import it.unitn.web.centodiciotto.utils.CustomDTFormatter;

import java.io.Serializable;
import java.util.Date;

/**
 * JavaBean for standardized Date/Time formatting across the application.
 */
public class CustomDTFormatterBean implements Serializable {

    private long date = -1L;

    /**
     * Gets the time since epoch associated to this Bean.
     *
     * @return the time since epoch associated to this Bean
     */
    public long getDate() {
        return date;
    }

    /**
     * Sets the time since epoch associated to this Bean.
     *
     * @param date the time since epoch associated to this Bean
     */
    public void setDate(long date) {
        this.date = date;
    }

    /**
     * Gets a date-only representation of the time since epoch.
     * <p>
     * The Date is formatted as "MMMM dd, yyyy" (example: December 19, 2000)
     *
     * @return the formatted date
     */
    public String getFormattedDate() {
        return CustomDTFormatter.formatDate(new Date(date));
    }

    /**
     * Gets a time-only representation of the time since epoch.
     * <p>
     * The time is formatted as "HH:MM" in 24H format (example: 20:05)
     *
     * @return the formatted time
     */
    public String getFormattedTime() {
        return CustomDTFormatter.formatTime(new Date(date));
    }

    /**
     * Gets a date and time representation of the time since epoch.
     * <p>
     * The Date is formatted as "MMMM dd, yyyy HH:MM" with the time in 24H format (example: December 19, 2000 20:05)
     *
     * @return the formatted date time
     */
    public String getFormattedDateTime() {
        return CustomDTFormatter.formatDateTime(new Date(date));
    }

}

src/main/java/it/unitn/web/centodiciotto/beans/entities/PatientDAOBean.java
package it.unitn.web.centodiciotto.beans.entities;

import it.unitn.web.centodiciotto.beans.BeanException;
import it.unitn.web.centodiciotto.persistence.dao.*;
import it.unitn.web.centodiciotto.persistence.dao.exceptions.DAOException;
import it.unitn.web.centodiciotto.persistence.dao.exceptions.DAOFactoryException;
import it.unitn.web.centodiciotto.persistence.dao.factories.DAOFactory;
import it.unitn.web.centodiciotto.persistence.dao.factories.jdbc.JDBCDAOFactory;
import it.unitn.web.centodiciotto.persistence.entities.*;
import it.unitn.web.centodiciotto.services.PhotoService;
import it.unitn.web.centodiciotto.services.ServiceException;
import it.unitn.web.centodiciotto.utils.entities.Pair;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * JavaBean representing a {@link PatientDAO} bound to a {@link Patient}.
 */
public class PatientDAOBean implements Serializable {
    private VisitDAO visitDAO = null;
    private PatientDAO patientDAO = null;
    private GeneralPractitionerDAO practitionerDAO = null;
    private DrugPrescriptionDAO drugPrescriptionDAO = null;
    private ExamDAO examDAO = null;

    private String patientID = null;

    private PhotoService photoService;

    /**
     * Initializes the bean.
     * <p>
     * Retrieves a DAOFactory implementation and then retrieves the DAOS.
     *
     * @param initializer a parameter required by the JavaBeans implementation that can be left to null.
     * @throws BeanException if errors during the DAO initialization occur
     */
    public void setInit(String initializer) throws BeanException {
        try {
            DAOFactory daoFactory = JDBCDAOFactory.getInstance();

            patientDAO = daoFactory.getDAO(PatientDAO.class);
            visitDAO = daoFactory.getDAO(VisitDAO.class);
            examDAO = daoFactory.getDAO(ExamDAO.class);
            practitionerDAO = daoFactory.getDAO(GeneralPractitionerDAO.class);
            drugPrescriptionDAO = daoFactory.getDAO(DrugPrescriptionDAO.class);

            photoService = PhotoService.getInstance();
        } catch (DAOFactoryException e) {
            throw new BeanException("Error in DAO retrieval: ", e);
        } catch (ServiceException e) {
            throw new BeanException("Error in initializing PhotoService: ", e);
        }
    }

    /**
     * Sets the patientID.
     *
     * @param patientID the patientID
     */
    public void setPatientID(String patientID) {
        this.patientID = patientID;
    }

    /**
     * Gets the {@link Patient} entity associated to this ID.
     *
     * @return the {@link Patient} entity associated to this ID
     * @throws BeanException thrown for any generic exception
     */
    public Patient getPatient() throws BeanException {
        Patient res;

        if (patientID == null) {
            throw new BeanException("PatientID is null");
        }

        try {
            res = patientDAO.getByPrimaryKey(patientID);
        } catch (DAOException e) {
            throw new BeanException("Error getting patient in patientDaoBean: ", e);
        }
        return res;
    }

    /**
     * Gets the {@link Photo} path associated with this {@link Patient}.
     *
     * @return a {@link String} representing the relative {@link Photo} path of the current {@link Patient}
     * @throws BeanException thrown for any generic exception
     */
    public String getPhotoPath() throws BeanException {
        if (patientID == null) {
            throw new BeanException("Practitioner is null");
        }

        try {
            return photoService.getLastPhoto(patientID);
        } catch (ServiceException e) {
            throw new BeanException("Error getting PhotoPath in patientDaoBean: ", e);
        }
    }

    /**
     * Gets a {@link List} of {@link Pair}s, each containing a {@link Photo} path associated with this {@link Patient},
     * and a {@link String} representing a fully-formatted date of upload for such photo, in antichronological order.
     *
     * @return a {@link List} of {@link Pair}s with photo paths and dates
     * @throws BeanException thrown for any generic exception
     */
    public List<Pair<String, String>> getAllPhotos() throws BeanException {
        if (patientID == null) {
            throw new BeanException("Practitioner is null");
        }

        try {
            return photoService.getAllPhotos(patientID);
        } catch (ServiceException e) {
            throw new BeanException("Error getting PhotoPath in patientDaoBean: ", e);
        }
    }

    /**
     * Gets all the {@link Exam}s done by this {@link Patient} in chronological order.
     *
     * @return a {@link List} of {@link Exam}s done by this patient, ordered chronologically
     * @throws BeanException thrown for any generic exception
     */
    public List<Exam> getExams() throws BeanException {
        if (patientID == null) {
            throw new BeanException("Practitioner is null");
        }

        try {
            return examDAO.getByPatient(patientID);
        } catch (DAOException e) {
            throw new BeanException("Error getting exams in patientDaoBean: ", e);
        }
    }

    /**
     * Gets all the {@link Visit}s done by this {@link Patient} in chronological order.
     *
     * @return a {@link List} of {@link Visit}s done by this patient, ordered chronologically
     * @throws BeanException thrown for any generic exception
     */
    public List<Visit> getDoneVisits() throws BeanException {
        if (patientID == null) {
            throw new BeanException("Practitioner is null");
        }

        try {
            return visitDAO.getDoneByPatient(patientID);
        } catch (DAOException e) {
            throw new BeanException("Error getting done visits in patientDaoBean: ", e);
        }
    }

    /**
     * Gets the pending {@link Visit}, if exists, for this {@link Patient}.
     *
     * @return the pending {@link Visit}, if exists, for this {@link Patient}
     * @throws BeanException thrown for any generic exception
     */
    public Visit getPendingVisit() throws BeanException {
        if (patientID == null) {
            throw new BeanException("Practitioner is null");
        }

        try {
            return visitDAO.getPendingByPractitionerAndPatient(getPatient().getPractitionerID(), patientID);
        } catch (DAOException e) {
            throw new BeanException("Error getting the pending Visit in patientDaoBean: ", e);
        }
    }

    /**
     * Gets this {@link Patient}'s {@link GeneralPractitioner}.
     *
     * @return the {@link Patient}'s associated {@link GeneralPractitioner}
     * @throws BeanException thrown for any generic exception
     */
    public GeneralPractitioner getPractitioner() throws BeanException {
        if (patientID == null) {
            throw new BeanException("Practitioner is null");
        }

        try {
            return practitionerDAO.getByPrimaryKey(getPatient().getPractitionerID());
        } catch (DAOException e) {
            throw new BeanException("Error getting exams in patientDaoBean: ", e);
        }
    }

    /**
     * Gets all this {@link Patient}'s {@link DrugPrescription}s.
     *
     * @return the {@link Patient}'s {@link DrugPrescription}s
     * @throws BeanException thrown for any generic exception
     */
    public List<DrugPrescription> getPrescriptions() throws BeanException {
        List<DrugPrescription> prescriptions;

        if (patientID == null) {
            throw new BeanException("Patient is null");
        }

        try {
            prescriptions = drugPrescriptionDAO.getByPatient(patientID);
        } catch (DAOException e) {
            throw new BeanException("Error getting unpaid Prescriptions in patientDaoBean: ", e);
        }
        return prescriptions;
    }

    /**
     * Gets this {@link Patient}'s done {@link Exam}s.
     *
     * @return the {@link Patient}'s done {@link Exam}s
     * @throws BeanException thrown for any generic exception
     */
    public List<Exam> getDoneExams() throws BeanException {
        List<Exam> exams;

        if (patientID == null) {
            throw new BeanException("Patient is null");
        }

        try {
            exams = examDAO.getDoneByPatient(patientID);
        } catch (DAOException e) {
            throw new BeanException("Error getting unpaid Exams in patientDaoBean: ", e);
        }
        return exams;
    }

    /**
     * Gets a {@link List} of potential {@link GeneralPractitioner}s for this Patient in this {@link Province}.
     *
     * @return a {@link List} of potential {@link GeneralPractitioner}s for this Patient in this {@link Province}
     * @throws BeanException thrown for any generic exception
     */
    public List<GeneralPractitioner> getAvailablePractitioners() throws BeanException {
        List<GeneralPractitioner> practitioners;
        List<GeneralPractitioner> chosenPractitioners = new ArrayList<>();

        if (patientID == null) {
            throw new BeanException("Patient is null");
        }

        try {
            GeneralPractitioner currentPractitioner = getPractitioner();
            practitioners = practitionerDAO.getByProvince(getPatient().getLivingProvince().getID());

            practitioners.stream().filter(practitioner -> !practitioner.getID().equals(currentPractitioner.getID()))
                    .forEach(chosenPractitioners::add);
        } catch (DAOException e) {
            throw new BeanException("Error getting unpaid Exams in patientDaoBean: ", e);
        }
        return chosenPractitioners;
    }

}

src/main/java/it/unitn/web/centodiciotto/servlets/patient/PhotoGalleryServlet.java
package it.unitn.web.centodiciotto.servlets.patient;

import it.unitn.web.centodiciotto.persistence.dao.PhotoDAO;
import it.unitn.web.centodiciotto.persistence.dao.exceptions.DAOException;
import it.unitn.web.centodiciotto.persistence.dao.exceptions.DAOFactoryException;
import it.unitn.web.centodiciotto.persistence.dao.factories.DAOFactory;
import it.unitn.web.centodiciotto.persistence.entities.Patient;
import it.unitn.web.centodiciotto.persistence.entities.Photo;
import it.unitn.web.centodiciotto.persistence.entities.User;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Timestamp;
import java.util.logging.Logger;

/**
 * PhotoGalleryRequest for handling requests to /restricted/patient/photo_gallery.
 * <p>
 * GET requests pass through.
 * <p>
 * POST requests take a photoID as a parameter and set the relative {@link Patient} photo as the current one.
 */
@SuppressWarnings({"FieldCanBeLocal", "unused", "DuplicatedCode"})
@WebServlet("/restricted/patient/photo_gallery")
public class PhotoGalleryServlet extends HttpServlet {

    private PhotoDAO photoDAO;

    private String contextPath;

    @Override
    public void init() throws ServletException {
        DAOFactory daoFactory = (DAOFactory) super.getServletContext().getAttribute("daoFactory");
        if (daoFactory == null) {
            throw new ServletException("DAOFactory is null.");
        }
        try {
            photoDAO = daoFactory.getDAO(PhotoDAO.class);
        } catch (DAOFactoryException e) {
            throw new ServletException("Error in DAO retrieval: ", e);
        }

        contextPath = getServletContext().getContextPath();
        if (!contextPath.endsWith("/")) {
            contextPath += "/";
        }
    }

    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        User user = (User) request.getSession().getAttribute("user");

        if (user instanceof Patient) {
            request.getRequestDispatcher("/jsp/patient/photo_gallery-p.jsp").forward(request, response);
        }
    }

    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        User user = (User) request.getSession().getAttribute("user");
        PrintWriter writer = response.getWriter();
        response.setContentType("application/json");


        if (user instanceof Patient) {
            Integer photoID;

            try {
                photoID = Integer.valueOf(request.getParameter("photoID"));
            } catch (NumberFormatException | NullPointerException e) {
                response.setStatus(400);
                String json = "{\"error\": \"Malformed input. Please try the photo again.\"}";
                writer.write(json);
                Logger.getLogger("C18").severe(json);
                return;
            }

            try {
                Photo chosenPhoto = photoDAO.getByPrimaryKey(photoID);
                chosenPhoto.setUploadDate(new Timestamp(System.currentTimeMillis()));
                photoDAO.update(chosenPhoto);

                if (!response.isCommitted()) {
                    response.sendRedirect(response.encodeRedirectURL(contextPath + "restricted/user"));
                }
            } catch (DAOException e) {
                throw new ServletException("Error in DAO usage: ", e);
            }
        }
    }
}

src/main/webapp/jsp/patient/change_practitioner-p.jsp
<%--suppress ELValidationInJSP --%>
<%@page contentType="text/html" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Unhappy with your practitioner? - CentoDiciotto</title>
    <%@ include file="/jsp/fragments/head.jsp" %>
    <style>
        @media (min-width: 992px) {
            /* Tabella principale */
            .table-cell.name {
                width: 40%;
            }

            .table-cell.city {
                width: 25%;
            }

            .table-cell.province {
                width: 15%;
            }

            .table-cell.action {
                width: 20%;
            }
        }
    </style>
    <script>
        $("document").ready(() => {
            const url = window.location.href;
            $("#table-select div").click(function () {
                $(this).find("input[type=radio]").prop("checked", true);
                $("#submit").removeAttr("disabled");
            });

            $("#practitioner").submit(function (e) {
                e.preventDefault();
                $("#submit").prop("disabled", true).html("Requesting change").startEllipsis();

                let form = $(this);
                let pract = $(".practitioner-id:checked");
                let data = form.serialize();

                $("input").prop("disabled", true);

                $.ajax({
                    type: "POST",
                    url: url,
                    cache: false,
                    data: data,
                    success: () => {
                        $("#current-practitioner").removeClass("chosen-practitioner");
                        $("#check").html("");
                        pract.parent().html("✔").parent().addClass("chosen-practitioner");
                        $("#title").html("Your practitioner change request has been receieved. " +
                            "You will receive a confirmation email soon.");
                        $("#message,#subtitle").slideUp();
                        $("#submit").stopEllipsis().html("Practitioner changed.");
                        $("#table-select div").off();
                    }
                });
            });
        });
    </script>
</head>
<body>
<%@ include file="/jsp/fragments/nav.jsp" %>
<div class="jumbotron mt-4">
    <h1>Unhappy with your practitioner?</h1>
    <p class="lead mt-4 mx-4" id="title">
        No worries. You can change it, as many times as you want, as long as it's employed in the same province.
    <p class="lead mx-4" id="subtitle">
        You can find your current practitioner first in the list, followed by all the available ones listed in
        alphabetical order.
    <p class="lead mx-4" id="message">
        To choose a practitioner, select the corresponding name and then confirm your changes clicking
        on the "I want to change my practitioner" button.
    </p>
</div>

<div class="container">
    <div class="body-content">
        <div class="row">
            <div class="col-md">
                <jsp:useBean id="patientDAO" class="it.unitn.web.centodiciotto.beans.entities.PatientDAOBean"/>
                <jsp:setProperty name="patientDAO" property="patientID" value="${sessionScope.user.ID}"/>
                <jsp:setProperty name="patientDAO" property="init" value=""/>
                <c:set var="practitioner" value="${patientDAO.practitioner}"/>

                <div id="table-select">
                    <div class="table-personal table-header">
                        <div class="table-cell name">Name</div>
                        <div class="table-cell city">City</div>
                        <div class="table-cell province">Province</div>
                        <div class="table-cell action">&nbsp;</div>
                    </div>
                    <div id="current-practitioner" class="table-personal chosen-practitioner">
                        <div class="table-cell name">${practitioner}</div>
                        <div class="table-cell city">${practitioner.workingPlace}</div>
                        <div class="table-cell province">${practitioner.workingProvince}</div>
                        <div id="check" class="table-cell action">✔</div>
                    </div>
                    <hr>
                    <form id="practitioner" method="POST">
                        <c:forEach items="${patientDAO.availablePractitioners}" var="availablePractitioner">
                            <div class="table-personal available">
                                <div class="table-cell name">${availablePractitioner}</div>
                                <div class="table-cell city">${availablePractitioner.workingPlace}</div>
                                <div class="table-cell province">${availablePractitioner.workingProvince}</div>
                                <div class="table-cell action">
                                    <input class="practitioner-id" type="radio" name="practitionerID"
                                           value="${availablePractitioner.ID}">
                                </div>
                            </div>
                            <hr>
                        </c:forEach>
                        <button id="submit" class="btn btn-personal btn-block text-center mt-4"
                                disabled type="submit">
                            I want to change my practitioner
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<%@ include file="/jsp/fragments/foot.jsp" %>
</body>

src/main/webapp/jsp/patient/photo_gallery-p.jsp
<%@page contentType="text/html" pageEncoding="UTF-8" %>

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Photo Gallery - CentoDiciotto</title>
    <%@ include file="/jsp/fragments/head.jsp" %>
    <script>
        $(document).ready(() => {
            $(".photo-path").each(function () {
                $(this).val(getID($(this).val()));
            });

            function getID(photoPath) {
                return parseInt(photoPath.split("/").slice(-1).toString().split(".")[0]);
            }
        });
    </script>
</head>
<body>
<%@ include file="/jsp/fragments/nav.jsp" %>
<div class="jumbotron mt-4">
    <h1>Profile Photos</h1>
    <p class="lead mt-4 mx-4">
        The following is a list of your past profile photos.<br>
        If you want to change your profile picture with an already uploaded image,
        you can select it from this gallery.
    </p>
</div>
<div class="container flex-wrap">
    <jsp:useBean id="patientDAO" class="it.unitn.web.centodiciotto.beans.entities.PatientDAOBean"/>
    <jsp:setProperty name="patientDAO" property="patientID" value="${sessionScope.user.ID}"/>
    <jsp:setProperty name="patientDAO" property="init" value=""/>

    <c:forEach items="${patientDAO.allPhotos}" var="pair">
        <c:set value="${pair.first}" var="photo"/>
        <c:set value="${pair.second}" var="date"/>
        <figure class="col-md">
            <img alt="picture" class="avatar img-fluid popup-opener" src="${pageContext.request.contextPath}/${photo}">
            <div class="popup-window">
                <div class="popup animate-in">
                    <form action="${pageContext.request.contextPath}/restricted/patient/photo_gallery"
                          class="photo-changer" method="POST">
                        <div id="message" class="mb-2 center-100">
                            Do you want to swap your profile photo with this?
                        </div>
                        <img class="avatar mb-2" src="${pageContext.request.contextPath}/${photo}" alt="${photo}">
                        <label>
                            <input type="text" hidden name="photoID" class="photo-path" value="${photo}">
                        </label>
                        <button class="btn btn-lg btn-block btn-personal mb-2" type="submit" id="submit">Change photo
                        </button>
                    </form>
                    <button class="btn btn-lg btn-block btn-secondary popup-closer">Exit</button>
                </div>
            </div>
            <figcaption style="font-size: 10pt; color: var(--118-darkest)">${date}</figcaption>
        </figure>
    </c:forEach>
</div>
<%@ include file="/jsp/fragments/foot.jsp" %>
</body>

src/main/webapp/jsp/patient/visits-p.jsp
<%--suppress ELValidationInJSP --%>
<%@page contentType="text/html" pageEncoding="UTF-8" %>
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Book your visit - CentoDiciotto</title>
    <%@ include file="/jsp/fragments/head.jsp" %>
    <style>
        @media (min-width: 992px) {
            .table-cell.practitioner {
                width: 40%;
            }

            .table-cell.date {
                width: 20%;
            }

            .table-cell.report-state {
                width: 15%;
            }

            .table-cell.action {
                width: 25%;
            }
        }
    </style>
    <script>
        $("document").ready(() => {
            const url = window.location.href;
            $("#book-visit").submit(function (e) {
                e.preventDefault();

                let form = $(this);
                let button = form.find("button");

                button.prop("disabled", true).html("Requesting...");

                $.ajax({
                    type: "POST",
                    url: url,
                    cache: false,
                    data: form.serialize(),
                    success: () => {
                        button.html("Successfully booked");
                    }
                });
            });
        });
    </script>
</head>
<body>
<%@ include file="/jsp/fragments/nav.jsp" %>

<div class="jumbotron mt-4">
    <h1>Book a visit!</h1>
    <p class="lead mt-4 mx-4">
        Here you can book a visit to your practitioner:
    </p>
</div>

<div style="text-align: center;" class="container">
    <div style="width: 50%; margin: auto">
        <jsp:useBean id="patientDAO"
                     class="it.unitn.web.centodiciotto.beans.entities.PatientDAOBean"/>
        <jsp:setProperty name="patientDAO" property="patientID"
                         value="${sessionScope.user.ID}"/>
        <jsp:setProperty name="patientDAO" property="init" value=""/>

        <c:set var="practitioner" value="${patientDAO.practitioner}"/>
        <c:set var="alreadyBooked" value="${!empty patientDAO.pendingVisit}"/>

        <h3>${practitioner}</h3>
        <form id="book-visit" method="post">
            <button class="btn btn-block btn-personal" type="submit"
            ${alreadyBooked ? "disabled" : ""}> ${alreadyBooked ? "Already booked" : "Book now"}
            </button>
        </form>
    </div>
</div>

<div class="jumbotron mt-4">
    <h1>Visit History</h1>
    <p class="lead mt-4 mx-4">
        Here you can see all the visits that you have done, and when the report will be avaiable
        you will be able to see it too.
    </p>
</div>

<div class="container">
    <div class="body-content">
        <div class="row">
            <div class="col-md">
                <div class="table-personal table-header">
                    <div class="table-cell practitioner">Practitioner</div>
                    <div class="table-cell date">Date</div>
                    <div class="table-cell report-state">Report State</div>
                    <div class="table-cell action">Report</div>
                </div>

                <jsp:useBean id="practitionerDAO"
                             class="it.unitn.web.centodiciotto.beans.entities.GeneralPractitionerDAOBean"/>
                <jsp:setProperty name="practitionerDAO" property="init" value=""/>

                <jsp:useBean id="visitDate" class="it.unitn.web.centodiciotto.beans.CustomDTFormatterBean"/>

                <c:forEach items="${patientDAO.doneVisits}" var="visit">
                    <c:if test="${visit.practitionerID ne practitioner.ID}">
                        <jsp:setProperty name="practitionerDAO" property="practitionerID"
                                         value="${visit.practitionerID}"/>
                        <c:set var="visitPractitioner" value="${practitionerDAO.practitioner}"/>
                    </c:if>

                    <jsp:setProperty name="visitDate" property="date" value="${visit.date.time}"/>
                    <div class="table-personal">
                        <div class="table-cell practitioner">
                            <c:if test="${visit.practitionerID ne practitioner.ID}">
                                ${visitPractitioner}
                            </c:if>
                            <c:if test="${visit.practitionerID eq practitioner.ID}">
                                ${practitioner}
                            </c:if>
                        </div>
                        <div class="table-cell date">${visitDate.formattedDateTime}</div>
                        <div class="table-cell report-state">${visit.reportAvailable ? "Available" : "Not available"}</div>
                        <div class="table-cell action">
                            <button type="button" class="btn btn-block btn-personal popup-opener"
                                ${visit.reportAvailable ? "" : "disabled"} >See Report
                            </button>
                            <div class="popup-window">
                                <div class="popup animate-in">
                                    <div>
                                        <h5>Visit report:</h5>
                                        <p>${visit.report}</p>
                                    </div>
                                    <button class="btn btn-lg btn-block btn-secondary popup-closer">Exit</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr>
                </c:forEach>
            </div>
        </div>
    </div>
</div>

<%@ include file="/jsp/fragments/foot.jsp" %>
</body>