src/main/java/it/unitn/web/centodiciotto/beans/CustomDTFormatterBean.java
package it.unitn.web.centodiciotto.beans;

import it.unitn.web.centodiciotto.utils.CustomDTFormatter;

import java.io.Serializable;
import java.util.Date;

/**
 * JavaBean for standardized Date/Time formatting across the application.
 */
public class CustomDTFormatterBean implements Serializable {

    private long date = -1L;

    /**
     * Gets the time since epoch associated to this Bean.
     *
     * @return the time since epoch associated to this Bean
     */
    public long getDate() {
        return date;
    }

    /**
     * Sets the time since epoch associated to this Bean.
     *
     * @param date the time since epoch associated to this Bean
     */
    public void setDate(long date) {
        this.date = date;
    }

    /**
     * Gets a date-only representation of the time since epoch.
     * <p>
     * The Date is formatted as "MMMM dd, yyyy" (example: December 19, 2000)
     *
     * @return the formatted date
     */
    public String getFormattedDate() {
        return CustomDTFormatter.formatDate(new Date(date));
    }

    /**
     * Gets a time-only representation of the time since epoch.
     * <p>
     * The time is formatted as "HH:MM" in 24H format (example: 20:05)
     *
     * @return the formatted time
     */
    public String getFormattedTime() {
        return CustomDTFormatter.formatTime(new Date(date));
    }

    /**
     * Gets a date and time representation of the time since epoch.
     * <p>
     * The Date is formatted as "MMMM dd, yyyy HH:MM" with the time in 24H format (example: December 19, 2000 20:05)
     *
     * @return the formatted date time
     */
    public String getFormattedDateTime() {
        return CustomDTFormatter.formatDateTime(new Date(date));
    }

}

src/main/java/it/unitn/web/centodiciotto/beans/entities/PatientDAOBean.java
package it.unitn.web.centodiciotto.beans.entities;

import it.unitn.web.centodiciotto.beans.BeanException;
import it.unitn.web.centodiciotto.persistence.dao.*;
import it.unitn.web.centodiciotto.persistence.dao.exceptions.DAOException;
import it.unitn.web.centodiciotto.persistence.dao.exceptions.DAOFactoryException;
import it.unitn.web.centodiciotto.persistence.dao.factories.DAOFactory;
import it.unitn.web.centodiciotto.persistence.dao.factories.jdbc.JDBCDAOFactory;
import it.unitn.web.centodiciotto.persistence.entities.*;
import it.unitn.web.centodiciotto.services.PhotoService;
import it.unitn.web.centodiciotto.services.ServiceException;
import it.unitn.web.centodiciotto.utils.entities.Pair;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * JavaBean representing a {@link PatientDAO} bound to a {@link Patient}.
 */
public class PatientDAOBean implements Serializable {
    private VisitDAO visitDAO = null;
    private PatientDAO patientDAO = null;
    private GeneralPractitionerDAO practitionerDAO = null;
    private DrugPrescriptionDAO drugPrescriptionDAO = null;
    private ExamDAO examDAO = null;

    private String patientID = null;

    private PhotoService photoService;

    /**
     * Initializes the bean.
     * <p>
     * Retrieves a DAOFactory implementation and then retrieves the DAOS.
     *
     * @param initializer a parameter required by the JavaBeans implementation that can be left to null.
     * @throws BeanException if errors during the DAO initialization occur
     */
    public void setInit(String initializer) throws BeanException {
        try {
            DAOFactory daoFactory = JDBCDAOFactory.getInstance();

            patientDAO = daoFactory.getDAO(PatientDAO.class);
            visitDAO = daoFactory.getDAO(VisitDAO.class);
            examDAO = daoFactory.getDAO(ExamDAO.class);
            practitionerDAO = daoFactory.getDAO(GeneralPractitionerDAO.class);
            drugPrescriptionDAO = daoFactory.getDAO(DrugPrescriptionDAO.class);

            photoService = PhotoService.getInstance();
        } catch (DAOFactoryException e) {
            throw new BeanException("Error in DAO retrieval: ", e);
        } catch (ServiceException e) {
            throw new BeanException("Error in initializing PhotoService: ", e);
        }
    }

    /**
     * Sets the patientID.
     *
     * @param patientID the patientID
     */
    public void setPatientID(String patientID) {
        this.patientID = patientID;
    }

    /**
     * Gets the {@link Patient} entity associated to this ID.
     *
     * @return the {@link Patient} entity associated to this ID
     * @throws BeanException thrown for any generic exception
     */
    public Patient getPatient() throws BeanException {
        Patient res;

        if (patientID == null) {
            throw new BeanException("PatientID is null");
        }

        try {
            res = patientDAO.getByPrimaryKey(patientID);
        } catch (DAOException e) {
            throw new BeanException("Error getting patient in patientDaoBean: ", e);
        }
        return res;
    }

    /**
     * Gets the {@link Photo} path associated with this {@link Patient}.
     *
     * @return a {@link String} representing the relative {@link Photo} path of the current {@link Patient}
     * @throws BeanException thrown for any generic exception
     */
    public String getPhotoPath() throws BeanException {
        if (patientID == null) {
            throw new BeanException("Practitioner is null");
        }

        try {
            return photoService.getLastPhoto(patientID);
        } catch (ServiceException e) {
            throw new BeanException("Error getting PhotoPath in patientDaoBean: ", e);
        }
    }

    /**
     * Gets a {@link List} of {@link Pair}s, each containing a {@link Photo} path associated with this {@link Patient},
     * and a {@link String} representing a fully-formatted date of upload for such photo, in antichronological order.
     *
     * @return a {@link List} of {@link Pair}s with photo paths and dates
     * @throws BeanException thrown for any generic exception
     */
    public List<Pair<String, String>> getAllPhotos() throws BeanException {
        if (patientID == null) {
            throw new BeanException("Practitioner is null");
        }

        try {
            return photoService.getAllPhotos(patientID);
        } catch (ServiceException e) {
            throw new BeanException("Error getting PhotoPath in patientDaoBean: ", e);
        }
    }

    /**
     * Gets all the {@link Exam}s done by this {@link Patient} in chronological order.
     *
     * @return a {@link List} of {@link Exam}s done by this patient, ordered chronologically
     * @throws BeanException thrown for any generic exception
     */
    public List<Exam> getExams() throws BeanException {
        if (patientID == null) {
            throw new BeanException("Practitioner is null");
        }

        try {
            return examDAO.getByPatient(patientID);
        } catch (DAOException e) {
            throw new BeanException("Error getting exams in patientDaoBean: ", e);
        }
    }

    /**
     * Gets all the {@link Visit}s done by this {@link Patient} in chronological order.
     *
     * @return a {@link List} of {@link Visit}s done by this patient, ordered chronologically
     * @throws BeanException thrown for any generic exception
     */
    public List<Visit> getDoneVisits() throws BeanException {
        if (patientID == null) {
            throw new BeanException("Practitioner is null");
        }

        try {
            return visitDAO.getDoneByPatient(patientID);
        } catch (DAOException e) {
            throw new BeanException("Error getting done visits in patientDaoBean: ", e);
        }
    }

    /**
     * Gets the pending {@link Visit}, if exists, for this {@link Patient}.
     *
     * @return the pending {@link Visit}, if exists, for this {@link Patient}
     * @throws BeanException thrown for any generic exception
     */
    public Visit getPendingVisit() throws BeanException {
        if (patientID == null) {
            throw new BeanException("Practitioner is null");
        }

        try {
            return visitDAO.getPendingByPractitionerAndPatient(getPatient().getPractitionerID(), patientID);
        } catch (DAOException e) {
            throw new BeanException("Error getting the pending Visit in patientDaoBean: ", e);
        }
    }

    /**
     * Gets this {@link Patient}'s {@link GeneralPractitioner}.
     *
     * @return the {@link Patient}'s associated {@link GeneralPractitioner}
     * @throws BeanException thrown for any generic exception
     */
    public GeneralPractitioner getPractitioner() throws BeanException {
        if (patientID == null) {
            throw new BeanException("Practitioner is null");
        }

        try {
            return practitionerDAO.getByPrimaryKey(getPatient().getPractitionerID());
        } catch (DAOException e) {
            throw new BeanException("Error getting exams in patientDaoBean: ", e);
        }
    }

    /**
     * Gets all this {@link Patient}'s {@link DrugPrescription}s.
     *
     * @return the {@link Patient}'s {@link DrugPrescription}s
     * @throws BeanException thrown for any generic exception
     */
    public List<DrugPrescription> getPrescriptions() throws BeanException {
        List<DrugPrescription> prescriptions;

        if (patientID == null) {
            throw new BeanException("Patient is null");
        }

        try {
            prescriptions = drugPrescriptionDAO.getByPatient(patientID);
        } catch (DAOException e) {
            throw new BeanException("Error getting unpaid Prescriptions in patientDaoBean: ", e);
        }
        return prescriptions;
    }

    /**
     * Gets this {@link Patient}'s done {@link Exam}s.
     *
     * @return the {@link Patient}'s done {@link Exam}s
     * @throws BeanException thrown for any generic exception
     */
    public List<Exam> getDoneExams() throws BeanException {
        List<Exam> exams;

        if (patientID == null) {
            throw new BeanException("Patient is null");
        }

        try {
            exams = examDAO.getDoneByPatient(patientID);
        } catch (DAOException e) {
            throw new BeanException("Error getting unpaid Exams in patientDaoBean: ", e);
        }
        return exams;
    }

    /**
     * Gets a {@link List} of potential {@link GeneralPractitioner}s for this Patient in this {@link Province}.
     *
     * @return a {@link List} of potential {@link GeneralPractitioner}s for this Patient in this {@link Province}
     * @throws BeanException thrown for any generic exception
     */
    public List<GeneralPractitioner> getAvailablePractitioners() throws BeanException {
        List<GeneralPractitioner> practitioners;
        List<GeneralPractitioner> chosenPractitioners = new ArrayList<>();

        if (patientID == null) {
            throw new BeanException("Patient is null");
        }

        try {
            GeneralPractitioner currentPractitioner = getPractitioner();
            practitioners = practitionerDAO.getByProvince(getPatient().getLivingProvince().getID());

            practitioners.stream().filter(practitioner -> !practitioner.getID().equals(currentPractitioner.getID()))
                    .forEach(chosenPractitioners::add);
        } catch (DAOException e) {
            throw new BeanException("Error getting unpaid Exams in patientDaoBean: ", e);
        }
        return chosenPractitioners;
    }

}

src/main/java/it/unitn/web/centodiciotto/persistence/entities/Patient.java
package it.unitn.web.centodiciotto.persistence.entities;

import java.sql.Timestamp;

/**
 * Patient entity. Represents the "patient" user class.
 * Subclasses {@link User} for authentication purposes.
 */
public class Patient extends User {
    private String firstName;
    private String lastName;
    private Timestamp birthDate;
    private String birthPlace;
    private String SSN;
    private Character gender;
    private Province livingProvince;
    private String livingPlace;
    private String practitionerID;

    /**
     * Gets the first name.
     *
     * @return the first name
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the first name.
     *
     * @param firstName the first name
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * Gets the last name.
     *
     * @return the last name
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the last name.
     *
     * @param lastName the last name
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * Gets the birth date.
     *
     * @return the birth date
     */
    public Timestamp getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the birth date.
     *
     * @param birthDate the birth date
     */
    public void setBirthDate(Timestamp birthDate) {
        this.birthDate = birthDate;
    }

    /**
     * Gets the birth place.
     *
     * @return the birth place
     */
    public String getBirthPlace() {
        return birthPlace;
    }

    /**
     * Sets the birth place.
     *
     * @param birthPlace the birth place
     */
    public void setBirthPlace(String birthPlace) {
        this.birthPlace = birthPlace;
    }

    /**
     * Gets the ssn.
     *
     * @return the ssn
     */
    public String getSSN() {
        return SSN;
    }

    /**
     * Sets the ssn.
     *
     * @param SSN the ssn
     */
    public void setSSN(String SSN) {
        this.SSN = SSN;
    }

    /**
     * Gets the gender.
     *
     * @return the gender
     */
    public Character getGender() {
        return gender;
    }

    /**
     * Sets the gender.
     *
     * @param gender the gender
     */
    public void setGender(Character gender) {
        this.gender = gender;
    }

    /**
     * Returns a full string representation of the gender.
     *
     * @return the gender as a string form
     */
    public String getFullGender() {
        return gender == 'F' ? "Female" : gender == 'M' ? "Male" : "Not specified";
    }

    /**
     * Gets the living province.
     *
     * @return the living province
     */
    public Province getLivingProvince() {
        return livingProvince;
    }

    /**
     * Sets the living province.
     *
     * @param livingProvince the living province
     */
    public void setLivingProvince(Province livingProvince) {
        this.livingProvince = livingProvince;
    }

    /**
     * Gets the living place.
     *
     * @return the living place
     */
    public String getLivingPlace() {
        return livingPlace;
    }

    /**
     * Sets the living place.
     *
     * @param livingPlace the living place
     */
    public void setLivingPlace(String livingPlace) {
        this.livingPlace = livingPlace;
    }

    /**
     * Gets the practitionerID
     *
     * @return the practitionerID
     */
    public String getPractitionerID() {
        return practitionerID;
    }

    /**
     * Sets the practitionerID
     *
     * @param practitionerID the practitionerID
     */
    public void setPractitionerID(String practitionerID) {
        this.practitionerID = practitionerID;
    }

    @Override
    public String toString() {
        return firstName + " " + lastName;
    }
}

src/main/java/it/unitn/web/centodiciotto/servlets/shared/LogoutServlet.java
package it.unitn.web.centodiciotto.servlets.shared;

import it.unitn.web.centodiciotto.persistence.entities.User;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import java.io.IOException;

/**
 * LogoutServlet for handling requests to /restricted/logout_handler.
 * <p>
 * GET and POST requests invalidate the session and redirect the user to the main page.
 */
@SuppressWarnings({"FieldCanBeLocal", "unused", "DuplicatedCode"})
@WebServlet("/restricted/logout_handler")
public class LogoutServlet extends HttpServlet {

    private String contextPath;

    @Override
    public void init() throws ServletException {
        contextPath = getServletContext().getContextPath();
        if (!contextPath.endsWith("/")) {
            contextPath += "/";
        }
    }

    private void processRequest(HttpServletRequest request, HttpServletResponse response) throws IOException {
        HttpSession session = request.getSession();
        User user = (User) session.getAttribute("user");

        if (user != null) {
            session.setAttribute("user", null);
            session.setAttribute("role", null);
            session.setAttribute("displayName", null);
            session.invalidate();

            response.sendRedirect(response.encodeRedirectURL(contextPath));
        }
    }

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }
}

src/main/webapp/jsp/shared/exam_history-hs-sd.jsp
<%--suppress ELValidationInJSP --%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8" %>
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Exam history - CentoDiciotto</title>
    <%@ include file="/jsp/fragments/head.jsp" %>
    <script src="${pageContext.request.contextPath}/js/table.js"></script>
    <style>
        @media (min-width: 992px) {
            .table-cell.avt {
                width: 7%;
            }

            .table-cell.name {
                width: 28%;
            }

            .table-cell.exam {
                width: 25%;
            }

            .table-cell.date {
                width: 25%;
            }

            .table-cell.action {
                width: 15%;
            }
        }
    </style>
    <script>
        $("document").ready(() => {
            const url = window.location.href;

            let tableHeaders = [
                {field: "avt", type: "photo", text: "&nbsp;"},
                {field: "name", type: "string", text: "Name"},
                {field: "exam", type: "string", text: "Exam"},
                {field: "date", type: "string", text: "Date"},
                {field: "action", type: "button", text: "&nbsp;"}
            ];

            $("#history-table").createTableHeaders(tableHeaders);
            renderPatientsRows();

            function renderPatientsRows() {
                $("#main-loading-container").slideDown();

                $.ajax({
                    type: "POST",
                    dataType: "json",
                    data: {
                        requestType: "examList",
                    },
                    url: url,
                    success: (data, textStatus, jqXHR) => {
                        let json = jqXHR.responseJSON;
                        $("#history-table").insertRows(tableHeaders, json, url);
                        $("#main-loading-container").slideUp();
                        enablePopup();
                    }
                });
            }

            $(document).ajaxSuccess(() => activateForm());

            function activateForm() {
                $(".submit-result").submit(function (e) {
                    e.preventDefault();

                    let form = $(this);
                    let button = form.find("button.submit-button");

                    button.prop("disabled", true).html("Sending...");

                    $.ajax({
                        type: "POST",
                        url: url,
                        cache: false,
                        data: form.serialize(),
                        success: () => {
                            button.html("Result updated");
                            setTimeout(() => {
                                button.prop("disabled", false).html("Submit result");
                            }, 2000);
                        }
                    });
                });
            }
        });
    </script>
</head>
<body>
<%@ include file="/jsp/fragments/nav.jsp" %>

<div class="jumbotron mt-4">
    <h1>Exam History</h1>
    <p class="lead mt-4 mx-4">
        In this section you can see all the exams already done.
        You can add or modify each exam's result.
    </p>
</div>

<div class="container">
    <div class="body-content">
        <div class="row">
            <div class="col-md">
                <div id="history-table"></div>
                <div class="justify-content-center loading" id="main-loading-container" style="text-align: center;">
                    <img class="rotating" role="status" style="width: 64px"
                         src="${pageContext.request.contextPath}/img/logo_blue.svg" alt="Loading..."/>
                </div>
            </div>
        </div>
    </div>
</div>
<%@ include file="/jsp/fragments/foot.jsp" %>
</body>

src/main/webapp/jsp/shared/user.jsp
<%@page contentType="text/html" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html lang="en">
<head>
    <title>User profile - CentoDiciotto</title>
    <%@ include file="/jsp/fragments/head.jsp" %>
    <script src="${pageContext.request.contextPath}/js/user.js"></script>
    <script src="${pageContext.request.contextPath}/js/newPassword.js"></script>
</head>
<body>
<%@ include file="/jsp/fragments/nav.jsp" %>
<div class="jumbotron">
    <h2 class="my-4">
        Welcome, ${sessionScope.displayName}.
    </h2>
    <c:if test="${sessionScope.role eq 'patient'}">
        <jsp:useBean id="patientDAO" class="it.unitn.web.centodiciotto.beans.entities.PatientDAOBean"/>
        <jsp:setProperty name="patientDAO" property="patientID" value="${sessionScope.user.ID}"/>
        <jsp:setProperty name="patientDAO" property="init" value=""/>

        <jsp:useBean id="birth" class="it.unitn.web.centodiciotto.beans.CustomDTFormatterBean"/>
        <jsp:setProperty name="birth" property="date" value="${sessionScope.user.birthDate.time}"/>

        <c:set var="practitioner" value="${patientDAO.practitioner}"/>
        <img class="avatar" src="${pageContext.request.contextPath}/${patientDAO.photoPath}" alt="">
    </c:if>
    <p class="lead mt-4 mx-4">
        To get started, use the navigation bar on top.
    </p>
</div>

<div class="container">
    <div class="body-content">
        <div class="row">
            <div class="col-md-6">
                <h3 class="my-4">
                    My information
                </h3>
                <table class="table table-unresponsive" style="margin: auto; overflow-wrap: break-word">
                    <c:choose>
                        <c:when test="${sessionScope.role eq 'patient'}">
                            <tr>
                                <th>Name</th>
                                <td>${sessionScope.user.firstName}</td>
                            </tr>
                            <tr>
                                <th>Surname</th>
                                <td>${sessionScope.user.lastName} </td>
                            </tr>
                            <tr>
                                <th>E-mail</th>
                                <td>${sessionScope.user.ID} </td>
                            </tr>
                            <tr>
                                <th>Gender</th>
                                <td>${sessionScope.user.fullGender}</td>
                            </tr>
                            <tr>
                                <th>SSN</th>
                                <td>${sessionScope.user.SSN} </td>
                            </tr>
                            <tr>
                                <th>Birthplace</th>
                                <td>${sessionScope.user.birthPlace} </td>
                            </tr>
                            <tr>
                                <th>Birthdate</th>
                                <td>${birth.formattedDate}</td>
                            </tr>
                            <tr>
                                <th>Living place</th>
                                <td>${sessionScope.user.livingPlace}</td>
                            </tr>
                            <tr>
                                <th>Living province</th>
                                <td>${sessionScope.user.livingProvince}</td>
                            </tr>
                            <tr>
                                <th>Practitioner</th>
                                <td>${practitioner}</td>
                            </tr>
                        </c:when>
                        <c:when test="${sessionScope.role eq 'general_practitioner'}">
                            <tr>
                                <th>Name</th>
                                <td>${sessionScope.user.firstName}</td>
                            </tr>
                            <tr>
                                <th>Surname</th>
                                <td>${sessionScope.user.lastName}</td>
                            </tr>
                            <tr>
                                <th>E-mail</th>
                                <td>${sessionScope.user.ID}</td>
                            </tr>
                            <tr>
                                <th>Working place</th>
                                <td>${sessionScope.user.workingPlace}</td>
                            </tr>
                            <tr>
                                <th>Working province</th>
                                <td>${sessionScope.user.workingProvince}</td>
                            </tr>
                        </c:when>
                        <c:when test="${sessionScope.role eq 'specialized_doctor'}">
                            <tr>
                                <th>Name</th>
                                <td>${sessionScope.user.firstName}</td>
                            </tr>
                            <tr>
                                <th>Surname</th>
                                <td>${sessionScope.user.lastName}</td>
                            </tr>
                            <tr>
                                <th>E-mail</th>
                                <td>${sessionScope.user.ID}</td>
                            </tr>
                            <tr>
                                <th>Working place</th>
                                <td>${sessionScope.user.workingPlace}</td>
                            </tr>
                        </c:when>
                        <c:when test="${sessionScope.role eq 'health_service'}">
                            <tr>
                                <th>Operating Province</th>
                                <td>${sessionScope.user.operatingProvince}
                                </td>
                            </tr>
                        </c:when>
                        <c:when test="${sessionScope.role eq 'chemist'}">
                            <tr>
                                <th>Name</th>
                                <td>${sessionScope.user.name} </td>
                            </tr>
                            <tr>
                                <th>E-mail</th>
                                <td>${sessionScope.user.ID} </td>
                            </tr>
                            <tr>
                                <th>Working place</th>
                                <td>${sessionScope.user.workingPlace}</td>
                            </tr>
                            <tr>
                                <th>Working province</th>
                                <td>${sessionScope.user.province} </td>
                            </tr>
                        </c:when>
                        <c:otherwise>
                            <tr>
                                <th>Error</th>
                                <td>Not supported yet</td>
                            </tr>
                        </c:otherwise>
                    </c:choose>
                </table>
            </div>
            <div class="col-md-6">
                <h3 class="my-4">
                    Change your password
                </h3>
                <form action="${pageContext.request.contextPath}/restricted/user"
                      id="password-change" method="POST">
                    <div class="form-label-group">
                        <input class="form-control mb-2" id="old-password" name="oldPassword"
                               placeholder="Insert your current password"
                               required type="password">
                        <input class="form-control mb-2" id="new-password" name="newPassword"
                               placeholder="Insert your new password"
                               required type="password">
                        <input class="form-control mb-2" id="new-password-confirm" name="newPasswordConfirm"
                               placeholder="Confirm your new password"
                               required type="password">
                        <input type="hidden" name="requestType" value="passwordChange">
                    </div>
                    <button id="password-change-button" class="btn btn-block mt-2 btn-personal" disabled type="submit">
                        Change password
                    </button>
                </form>
                <c:if test="${sessionScope.role eq 'patient'}">
                    <h3 class="my-4">
                        Change your profile picture
                    </h3>
                    <div class="input-group">
                        <form action="${pageContext.request.contextPath}/restricted/user"
                              id="avatar" class="center-100" method="POST" enctype="multipart/form-data">
                            <div class="custom-file" style="z-index: 0; text-align: left">
                                <input type="file" class="custom-file-input"
                                       name="avatarSelect" id="avatar-select" accept="image/png, image/jpeg">
                                <label class="custom-file-label" for="avatar-select">Choose file</label>
                                <input id="extension" type="hidden" name="extension" value="none">
                            </div>
                            <button class="btn btn-block mt-2 btn-personal" id="upload-avatar" type="submit">
                                Upload
                            </button>
                        </form>
                        <form class="center-100"
                              action="${pageContext.request.contextPath}/restricted/patient/photo_gallery">
                            <button class="btn btn-block mt-2 btn-personal" type="submit">
                                See gallery
                            </button>
                        </form>
                    </div>
                </c:if>
            </div>
        </div>
    </div>
</div>
<%@ include file="/jsp/fragments/foot.jsp" %>
</body>